---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In[2], line 16
     14 source_directory = f'./{dir_name}'
     15 output_file = f'collected_content_{dir_name}.txt'
---> 16 collect_content_to_single_file(source_directory, output_file)

Cell In[2], line 9, in collect_content_to_single_file(source_directory, output_file)
      6 header_str = f'\n# {str(file_path)}\n'
      8 outfile.write(header_str)
----> 9 outfile.write(infile.read())
     10 outfile.write('\n')

File ~\AppData\Local\Programs\Python\Python310\lib\codecs.py:322, in BufferedIncrementalDecoder.decode(self, input, final)
    319 def decode(self, input, final=False):
    320     # decode input (taking the buffer into account)
    321     data = self.buffer + input
--> 322     (result, consumed) = self._buffer_decode(data, self.errors, final)
    323     # keep undecoded input until the next call
    324     self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 8: invalid start byte